---
name: Package approbation image

"on":
  push:
    branches: [pkg]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and export to local Docker
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          tags: vegaprotocol/approbation:local

      - name: Sanity check docker image
        run: |
          docker run --rm vegaprotocol/approbation:local version || docker run --rm vegaprotocol/approbation:local

      - name: Build and push to GitHub Docker registry
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vegaprotocol/approbation:latest
            ghcr.io/vegaprotocol/approbation:${{github.ref_name}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Clean up old images
        uses: d22/cleanup-ghcr-containers-action@v0.3.3
        with:
          access-token: ${{ secrets.GH_CLEANUP_TOKEN }}
          package-name: 'ghcr.io/vegaprotocol/approbation'
          versions-to-keep: 3 
