name: publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Push release to npm (public)
        run: npm publish --access public .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
